### ISSUE TITLE
 File "WEB/python/xig.py", line 30, in ?///////////// Cant get it to start working

### ISSUE THREAD

**Issue by ezrah8634** [XBeeInternetGateway/XIG#49]
This is what gets returned when i type python xig.py in the digi esp's console;

#> python xig.py

Traceback (most recent call last):
  File "WEB/python/xig.py", line 30, in ?
    import library.logging_stub #@UnusedImport
ImportError: No module named library.logging_stub

#> 

I have a connectport X2 gateway and a Digi XBee-PRO® 900HP module.

I preformed these exact instructions;
https://github.com/XBeeInternetGateway/XIG/wiki/ConnectPort-Installation   

Thanks hope to hear something soon

**Comment by megadevcorp** [comment]
Hi, are you still working with XIG????
